workflows:
  android-debug:
    name: Android Debug Workflow
    max_build_duration: 60
    environment:
      groups:
        - android_sdk
    scripts:
      - name: Build Android APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
